export const graph = {
    'Abşeron': ['Bakı', 'Sumqayıt', 'Xızı', 'Qobustan', 'Hacıqabul'], 
    'Ağstafa': ['Qazax', 'Tovuz'], 
    'Ağcabədi': ['Bərdə', 'Zərdab', 'Füzuli', 'Ağdam', 'Xocavənd', 'Beyləqan'], 
    'Ağdaş': ['Bərdə', 'Yevlax', 'Qəbələ', 'Göyçay', 'Ucar', 'Zərdab','Şəki'], 
    'Ağdam': ['Xocalı', 'Kəlbəcər', 'Tərtər', 'Bərdə', 'Ağcabədi', 'Xocavənd'], 
    'Ağsu': ['Şamaxı', 'Hacıqabul', 'Kürdəmir', 'İsmayıllı'], 
    'Astara': ['Lənkəran', 'Lerik'], 
    'Bakı': ['Salyan', 'Hacıqabul', 'Abşeron', 'Sumqayıt'], 
    'Babək': ['Kəngərli', 'Şahbuz', 'Culfa', 'Naxçıvan','Zəngəzur'], 
    'Balakən': ['Zaqatala'], 
    'Bərdə': ['Yevlax', 'Ağdaş', 'Zərdab', 'Ağcabədi', 'Ağdam', 'Tərtər'], 
    'Beyləqan': ['Ağcabədi', 'Zərdab', 'Füzuli', 'İmişli'], 
    'Biləsuvar': ['İmişli', 'Saatlı', 'Sabirabad', 'Salyan', 'Neftçala', 'Cəlilabad'], 
    'Cəbrayıl': ['Zəngilan', 'Qubadlı', 'Xocavənd', 'Füzuli'], 
    'Cəlilabad': ['Biləsuvar', 'Salyan', 'Neftçala', 'Masallı', 'Yardımlı'], 
    'Culfa': ['Babək', 'Şahbuz', 'Ordubad','Zəngəzur'], 
    'Daşkəsən': ['Şəmkir', 'Kəlbəcər', 'Gədəbəy', 'Göygöl'], 
    'Füzuli': ['Cəbrayıl', 'Xocavənd', 'Ağcabədi', 'Beyləqan'],
    'Gəncə': ['Göygöl', 'Samux'], 
    'Gədəbəy': ['Tovuz', 'Şəmkir', 'Daşkəsən'], 
    'Goranboy': ['Samux', 'Göygöl', 'Kəlbəcər', 'Tərtər', 'Yevlax'], 
    'Göyçay': ['İsmayıllı', 'Kürdəmir', 'Ucar', 'Ağdaş','Qəbələ'], 
    'Göygöl': ['Gəncə', 'Samux', 'Goranboy', 'Kəlbəcər', 'Daşkəsən', 'Şəmkir'], 
    'Hacıqabul': ['Sabirabad', 'Kürdəmir', 'Ağsu', 'Şamaxı', 'Qobustan', 'Abşeron', 'Bakı', 'Salyan'], 
    'İmişli': ['Beyləqan', 'Zərdab', 'Kürdəmir', 'Sabirabad', 'Saatlı', 'Biləsuvar'], 
    'İsmayıllı': ['Quba', 'Şamaxı', 'Ağsu', 'Kürdəmir', 'Göyçay', 'Qəbələ'], 
    'Kəlbəcər': ['Daşkəsən', 'Göygöl', 'Goranboy', 'Tərtər', 'Ağdam', 'Xocalı', 'Laçın','Zəngəzur'], 
    'Kəngərli': ['Şərur', 'Babək','Zəngəzur'], 
    'Kürdəmir': ['Hacıqabul', 'Sabirabad', 'İmişli', 'Zərdab', 'Ucar', 'Göyçay', 'İsmayıllı', 'Ağsu'], 
    'Laçın': ['Kəlbəcər', 'Xocalı', 'Şuşa', 'Xocavənd', 'Qubadlı','Zəngəzur'], 
    'Lənkəran': ['Neftçala', 'Masallı', 'Lerik', 'Astara'], 
    'Lerik': ['Yardımlı', 'Masallı', 'Astara', 'Lənkəran'], 
    'Masallı': ['Lənkəran', 'Lerik', 'Yardımlı', 'Cəlilabad', 'Neftçala'], 
    'Mingəçevir': ['Yevlax'], 
    'Neftçala': ['Salyan', 'Biləsuvar', 'Cəlilabad', 'Masallı', 'Lənkəran'], 
    'Naxçıvan': ['Babək'], 
    'Oğuz': ['Şəki', 'Qəbələ'], 
    'Ordubad': ['Culfa','Zəngəzur'], 
    'Qəbələ': ['Oğuz', 'Qusar', 'Quba', 'İsmayıllı', 'Ağdaş', 'Göyçay','Şəki'], 
    'Qax': ['Zaqatala', 'Şəki', 'Yevlax', 'Samux'], 
    'Qazax': ['Ağstafa'], 
    'Quba': ['Qusar', 'Xaçmaz', 'Şabran', 'Şamaxı', 'İsmayıllı', 'Qəbələ'], 
    'Qubadlı': ['Laçın', 'Zəngilan', 'Xocavənd', 'Cəbrayıl','Zəngəzur'], 
    'Qobustan': ['Şamaxı', 'Xızı', 'Abşeron', 'Hacıqabul'], 
    'Qusar': ['Qəbələ', 'Quba', 'Xaçmaz'], 
    'Sabirabad': ['Saatlı', 'İmişli', 'Kürdəmir', 'Hacıqabul', 'Salyan', 'Biləsuvar'], 
    'Sədərək': ['Şərur'], 
    'Şahbuz': ['Babək', 'Culfa','Zəngəzur'], 
    'Şəki': ['Qax', 'Yevlax', 'Ağdaş', 'Qəbələ', 'Oğuz'], 
    'Salyan': ['Hacıqabul', 'Neftçala', 'Biləsuvar', 'Sabirabad', 'Bakı', 'Cəlilabad'], 
    'Şərur': ['Sədərək', 'Kəngərli','Zəngəzur'], 
    'Saatlı': ['Biləsuvar', 'İmişli', 'Sabirabad'], 
    'Şabran': ['Quba', 'Xaçmaz', 'Siyəzən','Şamaxı','Xızı'], 
    'Siyəzən': ['Şabran', 'Xızı'], 
    'Şəmkir': ['Tovuz', 'Gədəbəy', 'Daşkəsən', 'Göygöl', 'Samux'], 
    'Sumqayıt': ['Xızı', 'Abşeron', 'Bakı'], 
    'Şamaxı': ['Şabran', 'Quba', 'İsmayıllı', 'Ağsu', 'Hacıqabul', 'Qobustan', 'Xızı'], 
    'Samux': ['Gəncə', 'Göygöl', 'Şəmkir', 'Tovuz', 'Qax', 'Yevlax', 'Goranboy'], 
    'Şuşa': ['Xocalı', 'Xocavənd', 'Laçın'], 
    'Tərtər': ['Ağdam', 'Goranboy', 'Yevlax', 'Bərdə','Kəlbəcər'], 
    'Tovuz': ['Ağstafa', 'Şəmkir', 'Gədəbəy', 'Samux'], 
    'Ucar': ['Göyçay', 'Kürdəmir', 'Zərdab', 'Ağdaş'], 
    'Xaçmaz': ['Qusar', 'Quba', 'Şabran'], 
    'Xocalı': ['Laçın', 'Kəlbəcər', 'Ağdam', 'Xocavənd', 'Şuşa'], 
    'Xızı': ['Siyəzən', 'Quba', 'Şamaxı', 'Qobustan', 'Abşeron','Şabran','Sumqayıt'], 
    'Xocavənd': ['Ağdam', 'Ağcabədi', 'Füzuli', 'Cəbrayıl', 'Qubadlı', 'Laçın', 'Şuşa', 'Xocalı'], 
    'Yardımlı': ['Lerik', 'Masallı', 'Cəlilabad'], 
    'Yevlax': ['Ağdaş', 'Bərdə', 'Tərtər', 'Goranboy', 'Samux', 'Qax', 'Şəki','Mingəçevir'], 
    'Zəngilan': ['Qubadlı', 'Cəbrayıl','Zəngəzur'], 
    'Zaqatala': ['Balakən', 'Qax'], 
    'Zərdab': ['Ucar', 'Ağdaş', 'Bərdə', 'Ağcabədi', 'Beyləqan', 'İmişli', 'Kürdəmir'],
    'Zəngəzur': ['Kəlbəcər', 'Laçın', 'Qubadlı', 'Zəngilan', 'Ordubad', 'Culfa','Şahbuz','Babək','Kəngərli','Şərur']
    };
export const titleid= {
    "Abşeron": "AZ-ABS",
    "Ağstafa": "AZ-AGA",
    "Ağcabədi": "AZ-AGC",
    "Ağdaş": "AZ-AGS",
    "Ağdam": "AZ-AGM",
    "Ağsu": "AZ-AGU",
    "Astara": "AZ-AST",
    "Bakı": "AZ-BA",
    "Babək": "AZ-BAB",
    "Balakən": "AZ-BAL",
    "Bərdə": "AZ-BAR",
    "Beyləqan": "AZ-BEY",
    "Biləsuvar": "AZ-BIL",
    "Cəbrayıl": "AZ-CAB",
    "Cəlilabad": "AZ-CAL",
    "Culfa": "AZ-CUL",
    "Daşkəsən": "AZ-DAS",
    "Füzuli": "AZ-FUZ",
    "Gəncə": "AZ-GA",
    "Gədəbəy": "AZ-GAD",
    "Goranboy": "AZ-GOR",
    "Göyçay": "AZ-GOY",
    "Göygöl": "AZ-GYG",
    "Hacıqabul": "AZ-HAC",
    "İmişli": "AZ-IMI",
    "İsmayıllı": "AZ-ISM",
    "Kəlbəcər": "AZ-KAL",
    "Kəngərli": "AZ-KAN",
    "Kürdəmir": "AZ-KUR",
    "Laçın": "AZ-LAC",
    "Lənkəran": "AZ-LAN",
    "Lerik": "AZ-LER",
    "Masallı": "AZ-MAS",
    "Mingəçevir": "AZ-MI",
    "Neftçala": "AZ-NEF",
    "Naxçıvan": "AZ-NV",
    "Oğuz": "AZ-OGU",
    "Ordubad": "AZ-ORD",
    "Qəbələ": "AZ-QAB",
    "Qax": "AZ-QAX",
    "Qazax": "AZ-QAZ",
    "Quba": "AZ-QBA",
    "Qubadlı": "AZ-QBI",
    "Qobustan": "AZ-QOB",
    "Qusar": "AZ-QUS",
    "Sabirabad": "AZ-SAB",
    "Sədərək": "AZ-SAD",
    "Şahbuz": "AZ-SAH",
    "Şəki": "AZ-SAK",
    "Salyan": "AZ-SAL",
    "Şərur": "AZ-SAR",
    "Saatlı": "AZ-SAT",
    "Şabran": "AZ-SBN",
    "Siyəzən": "AZ-SIY",
    "Şəmkir": "AZ-SKR",
    "Sumqayıt": "AZ-SM",
    "Şamaxı": "AZ-SMI",
    "Samux": "AZ-SMX",
    "Şuşa": "AZ-SUS",
    "Tərtər": "AZ-TAR",
    "Tovuz": "AZ-TOV",
    "Ucar": "AZ-UCA",
    "Xaçmaz": "AZ-XAC",
    "Xocalı": "AZ-XCI",
    "Xızı": "AZ-XIZ",
    "Xocavənd": "AZ-XVD",
    "Yardımlı": "AZ-YAR",
    "Yevlax": "AZ-YEV",
    "Zəngilan": "AZ-ZAN",
    "Zaqatala": "AZ-ZAQ",
    "Zərdab": "AZ-ZAR",
    "Zəngəzur":"AZ-ZGR"
}
